# Site settings
title:              Zainab Alasadi
email:              hello@zainabalasadi.com
description: >-     
                    Hi, I'm Zainab Alasadi. Product Designer and Developer.
baseurl:            ""
url:                ""

# Build settings
markdown:           kramdown
kramdown:
   auto_ids:        false
permalink:          /:slug/

# Images
site_image:         "assets/images/site-image.png"
favicon-180:        "assets/images/site/favicon-180x180.png"
favicon-32:         "assets/images/site/favicon-32x32.png"
favicon-16:         "assets/images/site/favicon-16x16.png"

# Social
linkedin_username:  zainabalasadi
github_username:    zainabalasadi
medium_username:    zainabalasadi
instagram_username: zayalas
twitter_username:   ohhizainab

# Global style
style:              "ph6x-l ph5-m ph3 center pt6-l pt5"
post-style:         "ph6x-l ph5-m ph3 center pt5-l pt4"
small-text:         "f5"
remove-margin:      "mb0 mt0"

# Homepage
site-intro:         "w-100 w-100-m w-60-ns"
site-intro-margin:  "pb6-l pb5"
site-intro-space:   "w-100 w-100-m w-40-ns"
site-intro-text:    "f4 f3x-m f3x-l"
site-work-title:    "work"
site-hover-img:     "hover-item-show styled-list-img horizontal"
site-hover-div:     "hover-item dib mb5 mb5-m mb5-l"

# Footer
site-footer-margin: "pt5-l pt4 pb5-l pb4"
site-footer-email:  "work mb1"
site-footer-social: "f5"
site-footer-coded:  "f6 light pt2 mt0 mb4"

# Text
site-text-overline: "ttu tracked f6 f6-m f6-l"

# Case Studies
site-case-margin:   "center w-100 w-100-m w-60-ns"
site-case-header:   "mt5-l mt5 post-header"
site-case-title:    "f2-l f2 work mb3-l mb3 w-100 w-70-ns lh-title"
site-case-desc:     "fl w-100 w-100-m w-50-ns mb0-l mb4"
site-case-details:  "fr w-100 w-100-m w-25-ns"
site-case-image:    "mt55-l mt4 mb55-l mb4"
site-case-company:  "pb3"
site-case-break:    "mb5"
site-case-quote:    "f2-l f3 mb5 mt5"