# Site settings
title:              Zainab Alasadi
email:              hello@zainabalasadi.com
description: >-     
                    Hi, I'm Zainab Alasadi. Product Designer and Developer.
baseurl:            ""
url:                "http://127.0.0.1:4000"
site_image:         assets/images/site-image.png
linkedin_username:  zainabalasadi
github_username:    zainabalasadi
medium_username:    zainabalasadi
instagram_username: zayalas
twitter_username:   hizainab

# Build settings
markdown:           kramdown
kramdown:
   auto_ids:        false

style:              ph6-l ph4-m ph3 mt6-l mt5 mb5-l mb4 center
site-intro:         w-100 f7 f6-m f5-l
site-footer-sig:    fl w-100 w-60-ns
site-footer-social: socials tr fl w-100 w-40-ns



