# Site settings
title:              Zainab Alasadi
email:              hello@zainabalasadi.com
description: >-     
                    Hi, I'm Zainab Alasadi. Product Designer and Developer.
baseurl:            ""
url:                "http://127.0.0.1:4000"
site_image:         assets/images/site-image.png
linkedin_username:  zainabalasadi
github_username:    zainabalasadi
instagram_username: zayalas
twitter_username:   hizainab

# Build settings
markdown:           kramdown