# Site settings
title:              Zainab Alasadi
email:              hello@zainabalasadi.com
description: >-     
                    Hi, I'm Zainab Alasadi. Product Designer and Developer.
baseurl:            ""
url:                "http://127.0.0.1:4000"

# Build settings
markdown:           kramdown
kramdown:
   auto_ids:        false
permalink:          /:slug/

# Images
site_image:         "assets/images/site-image.png"
favicon-180:        "assets/images/site/favicon-180x180.png"
favicon-32:         "assets/images/site/favicon-32x32.png"
favicon-16:         "assets/images/site/favicon-16x16.png"

# Social
linkedin_username:  zainabalasadi
github_username:    zainabalasadi
medium_username:    zainabalasadi
instagram_username: zayalas
twitter_username:   hizainab

# Global style
style:              ph6-l ph4-m ph3 center pt6-l pt5 
site-intro:         w-100 w-100-m w-60-ns
site-intro-margin:  pb6-l pb5
site-intro-space:   w-100 w-100-m w-40-ns

site-footer-margin: pt5-l pt4 pb5-l pb4


