# Site settings
title:              Zainab Alasadi
email:              hello@zainabalasadi.com
description: >-     
                    Zainab Alasadi is a product designer and developer.
baseurl:            ""
url:                ""
google_analytics:   UA-118638009-1

# Build settings
markdown:           kramdown
kramdown:
   auto_ids:        false
permalink:          /:slug/

# Images
site_image:         "http://zainabalasadi.com/assets/images/site/site-image.png"
favicon-180:        "assets/images/site/favicon-180x180.png"
favicon-32:         "assets/images/site/favicon-32x32.png"
favicon-16:         "assets/images/site/favicon-16x16.png"

# Social
linkedin_username:  zainabalasadi
github_username:    zainabalasadi
medium_username:    zainabalasadi
instagram_username: zayalas
twitter_username:   ohhizainab

# Dev work
dev_work:           [{'product':'CensAus', 
                      'color':'#3E4596', 
                      'title':'Transforming census data into real narratives', 
                      'link': "https://github.com/zainabalasadi/CensAus",
                      'image':'assets/images/site/wave.jpg'},
                     {'product':'PractiCal', 
                      'color':'#566EE9', 
                      'title':'Calendar events through natural language', 
                      'link': "https://github.com/zainabalasadi/PractiCal",
                      'image':'assets/images/site/practical.jpg'},
                     {'product':"Here's Wally", 
                      'color':'#FF0000', 
                      'title':'Finding Wally using computer vision', 
                      'link': "https://github.com/zainabalasadi/PractiCal",
                      'image':'assets/images/site/wave.jpg'},
                     {'product':'ANDI', 
                      'color':'#6500FF', 
                      'title':'Smart clipboard for streamlining nuclear inspections', 
                      'link': "https://github.com/zainabalasadi/PractiCal",
                      'image':'assets/images/site/wave.jpg'}]

site-case-quote:    ".f2-l .f3 .mb5 .mt5"